spring:
  application:
    name: wanted-market

  datasource:
    url: jdbc:h2:mem:wanted-market
    driverClassName: org.h2.Driver
    username: sa
    password: password

  h2:
    console:
      enabled: true

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    show-sql: true

jwt:
  secret-key: "hongchae"